server:
  port: 8081
spring:
  data:
    mongodb:
      username: root
      password: changeinprod
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin