server:
  port: 8030
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: changeinprod
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8010/customer
    product-url: http://localhost:8020/product
    payment-url: http://localhost:8050/payment