services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeinprod
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices_net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeinprod
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - microservices_net
    restart: unless-stopped

  mail_dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices_net
    restart: unless-stopped

networks:
  microservices_net:
    driver: bridge

volumes:
  postgres:
  mongo: